// Generated by CoffeeScript 1.10.0
(function() {
  var Phaser, Signal;

  Phaser = this.Phaser;

  Signal = Phaser.Signal;

  Phaser.Sprite.prototype.damage = Phaser.Component.Health.prototype.damage = function(amount) {
    if (this.alive) {
      this.health -= amount;
      this.onDamaged.dispatch(amount, this.health, this.maxHealth, this);
      if (this.health <= 0) {
        this.kill();
      }
    }
    return this;
  };

  Object.defineProperty(Phaser.Sprite.prototype, "onDamaged", {
    get: function() {
      return this._onDamaged || (this._onDamaged = new Signal);
    }
  });

}).call(this);
